services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
#      - ${PWD}/allure-reports:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: "python:3.12-slim"
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/screenshots:/app/screenshots
    depends_on:
      - allure
      - allure-ui