services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - allure-results:/app/allure-results

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: ${HOST}
      STATIC_URL: ${STATIC_URL}
      IM_PRE: ${IM_PRE}
      IM_PROD: ${IM_PROD}
      WORKERS: 6
    image: python:3.12-slim
    command: /bin/bash -c run_docker.sh last_failed 4
    volumes:
      - allure-results:/app/allure-results
      - ./:/app
    depends_on:
      - allure
      - allure-ui

volumes:
  allure-results:
  app: